ERROR_CONTROLLER:
  class: 
  argument : []
DATABASE: 
  class: DevNoKage\Database
  argument : 
   - "%DB_DRIVE%" 
   - "%DB_HOST%" 
   - "%DB_PORT%" 
   - "%DB_NAME%" 
   - "%DB_USER%" 
   - "%DB_PASSWORD%" 